set(MIMXRT_FAMILY MIMXRT1052)
set(SOS_LIB_INCLUDE_DIRECTORIES include src ${MIMXRT_FAMILY} include/cmsis include/${MIMXRT_FAMILY})


file(GLOB MIMXRT_FAMILY_SOURCES ${CMAKE_SOURCE_DIR}/src/${MIMXRT_FAMILY}/*)
file(GLOB MIMXRT_VARIANT_SOURCES ${CMAKE_SOURCE_DIR}/src/${MIMXRT_VARIANT}/*.c)
file(GLOB MIMXRT_VARIANT_HEADERS ${CMAKE_SOURCE_DIR}/include/*${MIMXRT_FAMILY}.h ${CMAKE_SOURCE_DIR}/include/cmsis/${MIMXRT_FAMILY}.h ${CMAKE_SOURCE_DIR}/include/cmsis/${MIMXRT_FAMILY}_features.h include/${MIMXRT_FAMILY}/*.h)
set(SOS_LIB_SOURCELIST ${SHARED_SOURCELIST} ${MIMXRT_FAMILY_SOURCES} ${MIMXRT_VARIANT_SOURCES} ${MIMXRT_VARIANT_HEADERS})

set(SOS_LIB_OPTION mcu_${MIMXRT_VARIANT})
set(SOS_LIB_DEFINITIONS __${MIMXRT_VARIANT} ${MIMXRT_VARIANT_DEFINE}=1)
set(SOS_LIB_ARCH v7em_f5dh)

set(SOS_LIB_TYPE release)
include(${SOS_TOOLCHAIN_CMAKE_PATH}/sos-lib.cmake)
set(SOS_LIB_TYPE debug)
include(${SOS_TOOLCHAIN_CMAKE_PATH}/sos-lib.cmake)
